const dummyData = [
    {"first_name":"Frannie","last_name":"Shulem","email_id":"fshulem0@t.co","is_paid":false},
    {"first_name":"Roxi","last_name":"Gaukrodge","email_id":"rgaukrodge1@china.com.cn","is_paid":false},
    {"first_name":"Morgen","last_name":"Petford","email_id":"mpetford2@sina.com.cn","is_paid":false},
    {"first_name":"Fernanda","last_name":"Cud","email_id":"fcud3@bloomberg.com","is_paid":false},
    {"first_name":"Nickie","last_name":"Elkin","email_id":"nelkinn@fema.gov","is_paid":false},
    {"first_name":"Beulah","last_name":"Deek","email_id":"bdeekr@about.com","is_paid":false},
    {"first_name":"Sallee","last_name":"Wudeland","email_id":"swudelands@bing.com","is_paid":false},
    {"first_name":"Benton","last_name":"Itskovitz","email_id":"bitskovitzl@merriam-webster.com","is_paid":false},
    {"first_name":"Fabien","last_name":"St. Aubyn","email_id":"fstaubynm@loc.gov","is_paid":false},
    {"first_name":"Pamella","last_name":"Domleo","email_id":"pdomleoo@bloglines.com","is_paid":false},
    {"first_name":"Vassily","last_name":"Crothers","email_id":"vcrothersp@marketwatch.com","is_paid":false},
    {"first_name":"Gamaliel","last_name":"O'Caherny","email_id":"gocahernyq@sourceforge.net","is_paid":false},
    {"first_name":"Erna","last_name":"Cowup","email_id":"ecowup2t@examiner.com","is_paid":false},
    {"first_name":"Olivette","last_name":"McIlvenna","email_id":"omcilvenna2u@bing.com","is_paid":false},
    {"first_name":"Akash","last_name":"Patel","email_id":"ap@gmail.com","is_paid":false},
    {"first_name":"Dhananjay","last_name":"Patel","email_id":"dp@gmail.com","is_paid":false},
    {"first_name":"Akanksha","last_name":"Shukla","email_id":"as@yahoomail.com","is_paid":false},
    {"first_name":"Avikal","last_name":"Shukla","email_id":"avikal2@disqus.com","is_paid":false},
    {"first_name":"Rahul","last_name":"Katiyar","email_id":"rkatiyar@bloomerberg.com","is_paid":false},
    {"first_name":"Ablert","last_name":"Einstein","email_id":"e=m*c*c@sina.com","is_paid":false},
    {"first_name":"Wright","last_name":"Brothers","email_id":"aeroplane@fly.com","is_paid":false},
];

export {dummyData};